import type { Metadata } from "next";
import "./globals.css";
import NavSection from "../components/Navbar/Nav";

export const metadata: Metadata = {
  title: "Veya | WedPlans",
  description: "Generated by dezzDev",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      >
        <NavSection />
        {children}
      </body>
    </html>
  );
}
