import type { Metadata } from "next";
import { Inter, Plus_Jakarta_Sans } from "next/font/google";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });
const jakarta = Plus_Jakarta_Sans({ subsets: ["latin"], variable: "--font-jakarta" });

import "./globals.css";
import NavSection from "../components/Navbar/Nav";

import NetworkListener from "@/components/NetworkStatus/useNetworkStatus";
import NetworkToast from "@/components/NetworkStatus/NetworkToast";



export const metadata: Metadata = {
  title: "Veya | WedPlans",
  description: "Generated by dezzDev",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${inter.variable} ${jakarta.variable}`}>
      <body
      >
        <NavSection />
        <NetworkListener />
        <NetworkToast />
        {children}
      </body>
    </html>
  );
}
